### ISSUE TITLE
Minor mistake in Readme

### ISSUE THREAD

**Issue by AlexiZ** [netgen/javascript-cookie-control#1]
Hi,

I believe there is a small mistake in the README under section "**Parameters for cookie control config**". The sentence "*Parameters for each `options` object*" is written twice, and i'm guessing the second should be "*Parameters for each `optionalCookies` object*".

It's not breaking anything but since I saw it, well, here I am.

Thank you anyway, it's working really well for now :)

**Comment by gorangatuzo** [comment]
Hi @AlexiZ,
Yes, thanks for the heads up. It was a silly mistake but it's fixed now ;)
